language: go

go:
  - "1.11"
  - "stable"

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - go test ./... -v -race && cd examples && go test -v -race ./... && cd ..

env:
  - GO111MODULE=on
